defaultPlacement: end
enableVersioning: true
handle: home
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  9238c89c-b1ce-4b99-ae2a-359e5535abf0: # Fran√ßoise Nussbaumer
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: /
type: single
